### ISSUE TITLE
CSS 元素水平垂直居中

### ISSUE THREAD

**Issue by lingxiao-Zhu** [lingxiao-Zhu/blog#36]
## 行内元素
text-align + vertical-align + :after，支持定高定宽或者非定高定宽。
```html
<style>
  .parent {
    width: 400px;
    height: 400px;
    background-color: rosybrown;
    text-align: center;
  }
  .parent::after {
    content: '';
    display: inline-block;
    vertical-align: middle;
    height: 100%;
  }
  .child {
    vertical-align: middle;
    display: inline-block;
    height: 200px;
    width: 200px;
    background-color: red;
  }
</style>
<body>
  <div class="parent">
    <div class="child"></div>
  </div>
</body>
```
> vertical-align: middle
### 1、定高定宽 + 绝对定位 + margin:auto
```css
.box {
  width: 400px;
  height: 400px;
  background-color: saddlebrown;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  margin: auto;
}
```

### 2、定高定宽 + 绝对定位 + translate
```css
.box {
  width: 400px;
  height: 400px;
  background-color: saddlebrown;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate3d(-200px, -200px, 0);
}
```
### 3、定高定宽 + 绝对定位 + margin反向偏移
```css
.box {
  width: 400px;
  height: 400px;
  background-color: saddlebrown;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -200px;
  margin-left: -200px;
}
```
### 4、(非)定高定宽 + 父元素 flex 布局
```css
.parent {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
### 5、(非)定高定宽 + translate 负 50%
```css
.box {
    background-color: saddlebrown;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
```
### 6、(非)定高定宽 + grid布局
```css
.parent {
  display: grid;
  height: 500px;
  width: 500px;
}
.box {
  background-color: saddlebrown;
  justify-self: center;
  align-self: center;
}
```
