### ISSUE TITLE
CSS盒模型

### ISSUE THREAD

**Issue by lingxiao-Zhu** [lingxiao-Zhu/blog#8]
## 什么是盒模型
盒模型是包裹HTML元素的，由四个盒子组成：
- content box：展示元素内容的区域。
- padding box：清除内容周围的区域，是透明的。
- border box：边框区域，包裹 content 和 padding 区域。
- margin box：距离其他HTML元素的区域，也是透明的。

![image](https://user-images.githubusercontent.com/22609330/110439894-01c49200-80f3-11eb-85b5-64f59f2701b3.png)

### box-sizing
既然我们的元素布局是由四个盒子组成的，那么当我们设置 ***width***、***height*** 属性时，是设置哪个盒子的尺寸呢？

> 语法：box-sizing: content-box | border-box

#### content-box
默认值，width 与 height 只包括内容的宽和高， 不包括边框，内边距，外边距。 width = content-box

```css
.box{
   width: 100px;
   border: 10px solid #000;
   padding: 10px;
   margin: 10px;
   box-sizing: content-box;
}
```
此时的width只是content-box的宽度，所以元素的盒子总宽度 100+10*2+10*2+10*2 = 160px。

#### border-box
顾名思义，就是指元素高宽包含从 content-box 一直到 border-box。width = content-box + padding-box + border-box
```css
.box{
   width: 100px;
   border: 10px solid #000;
   padding: 10px;
   margin: 10px;
   box-sizing: content-box;
}
```
此时盒子总宽度 100 + margin的 10*2 = 120px。

**Comment by lingxiao-Zhu** [comment]
## box-sizing 为 border-box 时
### 当 width 大于 content + padding + border，那么 content 的宽度等于 width - padding - border。
```css
.box{
   width: 100px;
   border: 10px solid #000;
   padding: 10px;
   box-sizing: border-box;
}
```
![image](https://user-images.githubusercontent.com/22609330/110443275-b4e2ba80-80f6-11eb-86a7-b586ab6b6c8d.png)
> content = 100 - 10*2 - 10*2 = 60，和图中一样。

### 当 width 小于 content + padding + border，那么 content 的宽度等于 width - padding - border。
```css
.box{
   width: 20px;
   border: 10px solid #000;
   padding: 10px;
   box-sizing: border-box;
}
```
![image](https://user-images.githubusercontent.com/22609330/110443725-33d7f300-80f7-11eb-9992-a8e2b5f21feb.png)

> 可以看到 content 的宽度被压缩到了0，不过border和padding没影响，盒子模型被撑大了，等于 border + padding。
